# Generated by Django 2.2.1 on 2019-05-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='protfolio',
            new_name='portfolio',
        ),
    ]
